package com.delta.deltanet.models.service;

import com.delta.deltanet.models.entity.Contrato2024;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.Date;
import java.util.List;

public interface IContrato2024Service {
    public Contrato2024 Save (Contrato2024 contrato);
    Contrato2024 findById(Long id);
    Contrato2024 findByRelacion(Long id);
    Contrato2024 findByRelacion2(Long id);
    List<Object> listadoFiltrado(Long idRelacion, Long idTipoContrato, Long idTipoServicio, Long idFormaPago, String descripcion,
                                 Date fecIniRng1, Date fecIniRng2,
                                 Date fecFinRng1, Date fecFinRng2,Long estado);
    Page<Object> listadoFiltrado(Long idRelacion, Long idTipoContrato, Long idTipoServicio, Long idFormaPago, String descripcion,
                                 Date fecIniRng1, Date fecIniRng2,
                                 Date fecFinRng1, Date fecFinRng2, Long estado, Integer column, String dir, Pageable pageable);
    List<Object> listaContratos();
    List<Object> listaContratos(Date fecIni, Date fecFin);
    List<Object> listaContratos(Long idRelacion);
    List<Object> listaContratos1(Long idTipoCto);
    List<Object> listaContratos2(Long idTipoSrv);
    List<Object> listaContratos3(Long idFormaPgo);
    List<Object> listaContratos(String descrip);
    List<Object> listaContratos4(Long estado);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion);
    List<Object> listaContratos1(Date fecIni, Date fecFin, Long idtipoCto);
    List<Object> listaContratos2(Date fecIni, Date fecFin, Long idtipoSrv);
    List<Object> listaContratos3(Date fecIni, Date fecFin, Long idFormaPgo);
    List<Object> listaContratos(Date fecIni, Date fecFin, String descrip);
    List<Object> listaContratos4(Date fecIni, Date fecFin, Long estado);
    List<Object> listaContratos(Long idRelacion, Long idTipoCto);
    List<Object> listaContratos1(Long idRelacion, Long idTipoSrv);
    List<Object> listaContratos2(Long idRelacion, Long idFormaPgo);
    List<Object> listaContratos(Long idRelacion, String descrip);
    List<Object> listaContratos3(Long idRelacion, Long estado);
    List<Object> listaContratos4(Long idTipoCto, Long idTipoSrv);
    List<Object> listaContratos5(Long idTipoCto, Long idFormaPgo);
    List<Object> listaContratos1(Long idTipoCto, String descrip);
    List<Object> listaContratos6(Long idTipoCto, Long estado);
    List<Object> listaContratos7(Long idTipoSrv, Long idFormaPgo);
    List<Object> listaContratos2(Long idTipoSrv, String descrip);
    List<Object> listaContratos8(Long idTipoSrv, Long estado);
    List<Object> listaContratos3(Long idFormaPgo, String descrip);
    List<Object> listaContratos9(Long idFormaPgo, Long estado);
    List<Object> listaContratos(String descrip, Long estado);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto);
    List<Object> listaContratos1(Date fecIni, Date fecFin, Long idRelacion, Long idTipoSrv);
    List<Object> listaContratos2(Date fecIni, Date fecFin, Long idRelacion, Long idFormaPgo);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, String descrip);
    List<Object> listaContratos3(Date fecIni, Date fecFin, Long idRelacion, Long estado);
    List<Object> listaContratos4(Date fecIni, Date fecFin, Long idtipoCto, Long idTipoSrv);
    List<Object> listaContratos5(Date fecIni, Date fecFin, Long idtipoCto, Long idFormaPgo);
    List<Object> listaContratos1(Date fecIni, Date fecFin, Long idtipoCto, String descrip);
    List<Object> listaContratos6(Date fecIni, Date fecFin, Long idtipoCto, Long estado);
    List<Object> listaContratos7(Date fecIni, Date fecFin, Long idtipoSrv, Long idFormaPgo);
    List<Object> listaContratos2(Date fecIni, Date fecFin, Long idtipoSrv, String descrip);
    List<Object> listaContratos8(Date fecIni, Date fecFin, Long idtipoSrv, Long estado);
    List<Object> listaContratos3(Date fecIni, Date fecFin, Long idFormaPgo, String descrip);
    List<Object> listaContratos9(Date fecIni, Date fecFin, Long idFormaPgo, Long estado);
    List<Object> listaContratos(Date fecIni, Date fecFin, String descrip, Long estado);
    List<Object> listaContratos(Long idRelacion, Long idTipoCto, Long idTipoSrv);
    List<Object> listaContratos1(Long idRelacion, Long idTipoCto, Long idFormaPgo);
    List<Object> listaContratos(Long idRelacion, Long idTipoCto, String descrip);
    List<Object> listaContratos2(Long idRelacion, Long idTipoCto, Long estado);
    List<Object> listaContratos3(Long idRelacion, Long idTipoSrv, Long idFormaPgo);
    List<Object> listaContratos3(Long idRelacion, Long idTipoSrv, String descrip);
    List<Object> listaContratos4(Long idRelacion, Long idTipoSrv, Long estado);
    List<Object> listaContratos1(Long idRelacion, Long idFormaPgo, String descrip);
    List<Object> listaContratos5(Long idRelacion, Long idFormaPgo, Long estado);
    List<Object> listaContratos(Long idRelacion, String descrip, Long estado);
    List<Object> listaContratos6(Long idTipoCto, Long idTipoSrv, Long idFormaPgo);
    List<Object> listaContratos2(Long idTipoCto, Long idTipoSrv, String descrip);
    List<Object> listaContratos7(Long idTipoCto, Long idTipoSrv, Long estado);
    List<Object> listaContratos4(Long idTipoCto, Long idFormaPgo, String descrip);
    List<Object> listaContratos8(Long idTipoCto, Long idFormaPgo, Long estado);
    List<Object> listaContratos1(Long idTipoCto, String descrip, Long estado);
    List<Object> listaContratos5(Long idTipoSrv, Long idFormaPgo, String descrip);
    List<Object> listaContratos9(Long idTipoSrv, Long idFormaPgo, Long estado);
    List<Object> listaContratos2(Long idTipoSrv, String descrip, Long estado);
    List<Object> listaContratos3(Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idTipoSrv);
    List<Object> listaContratos1(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idFormaPgo);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, String descrip);
    List<Object> listaContratos2(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long estado);
    List<Object> listaContratos3(Date fecIni, Date fecFin, Long idRelacion, Long idTipoSrv, Long idFormaPgo);
    List<Object> listaContratos1(Date fecIni, Date fecFin, Long idRelacion, Long idTipoSrv, String descrip);
    List<Object> listaContratos4(Date fecIni, Date fecFin, Long idRelacion, Long idTipoSrv, Long estado);
    List<Object> listaContratos2(Date fecIni, Date fecFin, Long idRelacion, Long idFormaPgo, String descrip);
    List<Object> listaContratos5(Date fecIni, Date fecFin, Long idRelacion, Long idFormaPgo, Long estado);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, String descrip, Long estado);
    List<Object> listaContratos6(Date fecIni, Date fecFin, Long idtipoCto, Long idTipoSrv, Long idFormaPgo);
    List<Object> listaContratos3(Date fecIni, Date fecFin, Long idtipoCto, Long idTipoSrv, String descrip);
    List<Object> listaContratos7(Date fecIni, Date fecFin, Long idtipoCto, Long idTipoSrv, Long estado);
    List<Object> listaContratos4(Date fecIni, Date fecFin, Long idtipoCto, Long idFormaPgo, String descrip);
    List<Object> listaContratos8(Date fecIni, Date fecFin, Long idtipoCto, Long idFormaPgo, Long estado);
    List<Object> listaContratos1(Date fecIni, Date fecFin, Long idtipoCto, String descrip, Long estado);
    List<Object> listaContratos5(Date fecIni, Date fecFin, Long idtipoSrv, Long idFormaPgo, String descrip);
    List<Object> listaContratos9(Date fecIni, Date fecFin, Long idtipoSrv, Long idFormaPgo, Long estado);
    List<Object> listaContratos2(Date fecIni, Date fecFin, Long idtipoSrv, String descrip, Long estado);
    List<Object> listaContratos3(Date fecIni, Date fecFin, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos(Long idRelacion, Long idTipoCto, Long idTipoSrv, Long idformaPgo);
    List<Object> listaContratos(Long idRelacion, Long idTipoCto, Long idTipoSrv, String descrip);
    List<Object> listaContratos1(Long idRelacion, Long idTipoCto, Long idTipoSrv, Long estado);
    List<Object> listaContratos1(Long idRelacion, Long idTipoCto, Long idFormaPgo,String descrip);
    List<Object> listaContratos2(Long idRelacion, Long idTipoCto, Long idFormaPgo,Long estado);
    List<Object> listaContratos(Long idRelacion, Long idTipoCto, String descrip, Long estado);
    List<Object> listaContratos2(Long idRelacion, Long idTipoSrv, Long idFormaPgo, String descrip);
    List<Object> listaContratos3(Long idRelacion, Long idTipoSrv, Long idFormaPgo, Long estado);
    List<Object> listaContratos1(Long idRelacion, Long idTipoSrv, String descrip, Long estado);
    List<Object> listaContratos2(Long idRelacion, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos3(Long idTipoCto, Long idTipoSrv, Long idFormaPgo, String descrip);
    List<Object> listaContratos4(Long idTipoCto, Long idTipoSrv, Long idFormaPgo, Long estado);
    List<Object> listaContratos3(Long idTipoCto, Long idTipoSrv, String descrip, Long estado);
    List<Object> listaContratos4(Long idTipoCto, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos5(Long idTipoSrv, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idTipoSrv, Long idFormaPgo);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idTipoSrv, String descrip);
    List<Object> listaContratos1(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idTipoSrv, Long estado);
    List<Object> listaContratos1(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idFormaPgo, String descrip);
    List<Object> listaContratos2(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idFormaPgo, Long estado);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, String descrip, Long estado);
    List<Object> listaContratos3(Date fecIni, Date fecFin, Long idRelacion, Long idTipoSrv, Long idFormaPgo, String descrip);
    List<Object> listaContratos3(Date fecIni, Date fecFin, Long idRelacion, Long idTipoSrv, Long idFormaPgo, Long estado);
    List<Object> listaContratos1(Date fecIni, Date fecFin, Long idRelacion, Long idTipoSrv, String descrip, Long estado);
    List<Object> listaContratos2(Date fecIni, Date fecFin, Long idRelacion, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos6(Date fecIni, Date fecFin, Long idtipoCto, Long idTipoSrv, Long idFormaPgo, String descrip);
    List<Object> listaContratos6(Date fecIni, Date fecFin, Long idtipoCto, Long idTipoSrv, Long idFormaPgo, Long estado);
    List<Object> listaContratos3(Date fecIni, Date fecFin, Long idtipoCto, Long idTipoSrv, String descrip, Long estado);
    List<Object> listaContratos4(Date fecIni, Date fecFin, Long idtipoCto, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos5(Date fecIni, Date fecFin, Long idtipoSrv, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos(Long idRelacion, Long idTipoCto, Long idTipoSrv, Long idformaPgo, String descrip);
    List<Object> listaContratos(Long idRelacion, Long idTipoCto, Long idTipoSrv, Long idformaPgo, Long estado);
    List<Object> listaContratos(Long idRelacion, Long idTipoCto, Long idTipoSrv, String descrip,Long estado);
    List<Object> listaContratos1(Long idRelacion, Long idTipoCto, Long idFormaPgo,String descrip, Long estado);
    List<Object> listaContratos2(Long idRelacion, Long idTipoSrv, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos3(Long idTipoCto, Long idTipoSrv, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idTipoSrv, Long idFormaPgo, String descrip);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idTipoSrv, Long idFormaPgo, Long estado);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idTipoSrv, String descrip, Long estado);
    List<Object> listaContratos1(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idFormaPgo, String descrip,Long estado);
    List<Object> listaContratos3(Date fecIni, Date fecFin, Long idRelacion, Long idTipoSrv, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos6(Date fecIni, Date fecFin, Long idtipoCto, Long idTipoSrv, Long idFormaPgo, String descrip, Long estado);
    List<Object> listaContratos(Long idRelacion, Long idTipoCto, Long idTipoSrv, Long idformaPgo, String descrip, Long estado);
    List<Object> listaContratos(Date fecIni, Date fecFin, Long idRelacion, Long idTipoCto, Long idTipoSrv, Long idFormaPgo, String descrip, Long estado);
    Object buscaCliente(Long id);

}
